<?php

/**
 * Implements hook_init().
 */
function tpc_general_init() {
  drupal_add_js(drupal_get_path('module', 'tpc_general') . '/tpc_general.js');
  drupal_add_css(drupal_get_path('module', 'tpc_general') . '/tpc_general.css');
  include_once('tpc_general.seven_theme.inc');
}

/**
 * Implements hook_menu().
 */
function tpc_general_menu() {
  $items = array(
    'google77fb9b8c2bc767f8.html' => array(
      'title' => 'Google Webmaster Tools verification file',
      'page callback' => 'tpc_general_gwt_verification',
      'page arguments' => array('google77fb9b8c2bc767f8'),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ),
    'googled8b6d4569de16b0f.html' => array(
      'title' => 'Google Webmaster Tools verification file',
      'page callback' => 'tpc_general_gwt_verification',
      'page arguments' => array('googled8b6d4569de16b0f'),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ),
    'BingSiteAuth.xml' => array(
      'title' => 'Bing Webmaster verification file',
      'page callback' => 'tpc_general_bing_verification',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ),
  );
  $items['admin/config/system/tpc_general'] = array(
    'title' => 'TPC General settings',
    'description' => 'Custom configuration options used by TPC staff.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tpc_general_admin_settings_form'),
    'access callback' => 'tpc_general_admin_access',
    'file' => 'tpc_general.admin.inc',
  );
  $items['tpc_general/heartbeat'] = array(
    'title' => 'TPC phone home',
    'description' => 'A poor man\'s heartbeat module implementation.',
    'page callback' => 'tpc_general_heartbeat_report',
    'access callback' => 'tpc_general_heartbeat_access',
    'file' => 'tpc_general.admin.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Access callback for TPC reporting function. Restricts access by IP address.
 */
function tpc_general_heartbeat_access() {
  $allowed_ips = variable_get('tpc_general_wiki_ip', '209.240.78.13,209.240.68.25,209.240.68.26');
  $allowed_ips = explode(',', $allowed_ips);
  if (in_array($_SERVER['REMOTE_ADDR'], $allowed_ips)) {
    return TRUE;
  }
  return FALSE;
}

// Access callback for settings form. Restricts access to superuser for now.
function tpc_general_admin_access() {
  global $user;
  if ($user->uid == 1) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Output the Google Webmaster Tools verification string for TPC's account.
 */
function tpc_general_gwt_verification($id) {
  echo "google-site-verification: $id.html";
}

/**
 * Output the Bing Webmaster verification string for TPC's account.
 */
function tpc_general_bing_verification() {
  drupal_add_http_header('Content-Type', 'application/xml');
  echo '<?xml version="1.0"?>
<users>
        <user>4DC24E4DF802F9070802BE81B10F6C08</user>
</users>';
}

/**
 * Implements hook_form_alter().
 *
 * Expose the body summary sub-field by default on node edit forms.
 */
function tpc_general_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($form['#node_edit_form'])) {
    drupal_add_js('jQuery(function(){jQuery(".form-item-body-und-0-value .link-edit-summary").click();});', array('type' => 'inline', 'scope' => 'footer', 'weight' => 5));
  }
}

/**
 * Implements hook_preprocess_node().
 *
 * Use body summary for META description tag, if available.
 */
function tpc_general_preprocess_node(&$vars) {
  // Only do this when viewing single nodes; hence checking arg(0).
  if (arg(0) == 'node' && !empty($vars['body'][0]['summary'])) {
    $description = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'description' => check_plain($vars['body'][0]['summary']),
      ),
    );
    drupal_add_html_head($description, 'tpc_general_meta_description');
  }  
}

/**
 * Implements hook_field_formatter_info().
 *
 * Add a text formatter similar to plain text, but with HTML line breaks.
 */
function tpc_general_field_formatter_info() {
  return array(
    'text_plain_linebreaks' => array(
      'label' => t('Plain text with linebreaks'),
      'field types' => array('text_long', 'text_with_summary'),
    ),
  );
}

function tpc_general_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'text_plain_linebreaks':
      foreach ($items as $delta => $item) {
        $element[$delta] = array('#markup' => nl2br(strip_tags($item['value'])));
      }
      break;
  }
  return $element;
}
  
/**
 * Display the relative filepath for file fields.
 */
function tpc_general_preprocess_file_widget_multiple(&$vars) {
  foreach(element_children($vars['element']) AS $key) {
    if (!empty($vars['element'][$key]['#default_value']['uri'])) {
      $file_public_path = '/' . variable_get('file_public_path', 'sites/default/files') . '/';
      $relative = str_replace('public://', $file_public_path, $vars['element'][$key]['#default_value']['uri']);
      $vars['element'][$key]['filename']['#suffix'] = '<div class="file-relative-path">' . $relative . '</div>';
    }
  }
}

/**
 * Implements hook_views_api().
 */
function tpc_general_views_api() {
  return array(
    'api' => '3',
  );
}

/**
 * Implements hook_cron().
 *
 * If the TPC Wiki Node ID for this site is known, update the wiki.
 * Uses the wiki's XML-RPC server defined by tpc_siteinfo.module.
 */
function tpc_general_cron() {
  $site_nid = variable_get('tpc_general_heartbeat_site_nid', FALSE);
  if (is_numeric($site_nid)) {
    module_load_include('inc', 'tpc_general', 'tpc_general.admin');
    $url = variable_get('tpc_general_heartbeat_url', 'https://www.tripark.org/wiki/xmlrpc.php');
    $data = tpc_general_heartbeat_data();
    $options = array();
    $options['tpc_siteinfo.stethoscope'] = array((int)$site_nid, $data);
    $request = xmlrpc($url, $options);
  }
}

/**
 * Implements hook_action_info().
 *
 * Necessary for Views Bulk Operations integration.
 */
function pathauto_action_info() {
  return array(
    'pathauto_node_update_action' => array(
      'type' => 'node',
      'label' => t('Update node alias'),
      'configurable' => FALSE,
      'triggers' => array('node_insert', 'node_update'),
    ),
    'pathauto_user_update_action' => array(
      'type' => 'user',
      'label' => t('Update user alias'),
      'configurable' => FALSE,
      'triggers' => array('user_insert', 'user_update'),
    ),
  );
}

/**
 * Update action wrapper for pathauto_node_update_alias().
 */
function pathauto_node_update_action($node, $context = array()) {
  pathauto_node_update_alias($node, 'bulkupdate', array('message' => TRUE));
}

/**
 * Update action wrapper for pathauto_user_update_alias().
 */
function pathauto_user_update_action($user, $context = array()) {
  pathauto_user_update_alias($user, 'bulkupdate', array('message' => TRUE));
}

